name: pomodore
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # theming
  cupertino_icons: ^1.0.2
  bitsdojo_window: ^0.1.5
  google_fonts: ^3.0.1
  ionicons: ^0.2.1
  flutter_spinkit: ^5.1.0

  # state management
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5

  # dependency injection
  get_it: ^7.2.0

  # database and storage
  hive_flutter: ^1.1.0
  sqflite: ^2.2.1
  path_provider: ^2.0.11
  flutter_secure_storage: ^7.0.1

  # generators
  uuid: ^3.0.7

  # calenders
  calendar_timeline: ^1.0.5
  timeline_tile: ^2.0.0
  date_time_line: ^0.0.3

  # charts
  flutter_heatmap_calendar: ^1.0.5
  syncfusion_flutter_charts: ^20.3.52

  # utility
  intl: ^0.17.0
  flutter_datetime_picker: ^1.5.1
  dartz: ^0.10.1

  # sensors
  vibration: ^1.7.6
  audio_manager: ^0.8.2

dev_dependencies:
  test: ^1.16.0
  flutter_lints: ^2.0.0
  build_runner: ^2.3.0
  bloc_test: ^9.0.0
  mockito: ^5.3.2
  flutter_test:
    sdk: flutter



flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
