name: Release

on:
  push:
    branches: [main, develop, feature/apk-uploader]

jobs:
  build_android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v1

      - name: Setup java to compile android project
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Install and set flutter version
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.0"
          channel: "stable"

      - name: Check dir
        run: ls /home/runner/work

      - name: Create the keystore
        run: echo "${{ secrets.KEY }}" | base64 -d > ./android/key.jks

      - name: Create the properties
        run: echo "${{ secrets.PROPERTIES }}" | base64 -d > ./android/key.properties

      - name: Get packages
        run: flutter pub get

      - name: Run tests
        run: flutter test

      - name: Build android app
        run: |
          flutter build apk --split-per-abi --release
          ls -lh build/app/outputs/apk/release/

      - name: Setup Telegram Action
        uses: appleboy/telegram-action@master
        with:
          server_url: "https://api.telegram.org"
          token: ${{ secrets.BOT_ID }}
          to: ${{ secrets.CHAT_ID }}
          message: "New release is available!"
          files: |
            build/app/outputs/apk/release/*-release.apk
